package io.graversen.rust.rcon.protocol.util;

public enum WorldEvents {
    AIRDROP,
    CARGO_SHIP_HARBOR_APPROACH,
    CARGO_SHIP_HARBOR_ARRIVED,
    CARGO_SHIP_HARBOR_LEFT,
    CARGO_PLANE,
    CH47_SCIENTISTS,
    LOCKED_CRATE_HACK_COMPLETED,
    LOCKED_CRATE_HACK_STARTED,
    LOCKED_CRATE_LANDED,
    PATROL_HELICOPTER,
    SUPPLY_DROP_DROPPED,
    SUPPLY_DROP_LANDED,
    UNKNOWN;
}
